version: '3.8'

services:
  drupal_local:
    image: drupal:8.9.1-apache
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes
    restart: always

  pg_db:
    image: postgres:12.3-alpine
    environment: 
      POSTGRES_DB: drupal 
      POSTGRES_USER: suriya
      POSTGRES_PASSWORD: suriya
    volumes:
      - drupal_db:/var/lib/postgresql/data 
    restart: always

volumes: 
 drupal_modules: 
 drupal_sites: 
 drupal_profiles: 
 drupal_themes: 
 drupal_db:  