## Docker-Mastery Course Secret Assingment 1
## Author : SURIYAKUMAR RAJARJAN

version: '3.8'

services:
  postgres:
    image: postgres:alpine
    secrets:
      - psql_user
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER_FILE: /run/secrets/psql_user
    

secrets:
  psql_user:
    file: ./psql_user.txt
  psql_password:
    file: ./psql_password.txt
